server.port=18082
spring.application.name=order-service
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.data.redis.host=localhost
spring.data.redis.port=16379
rocketmq.name-server=localhost:9876
rocketmq.producer.group=order-service-producer
snowflake.worker-id=3
snowflake.data-center-id=1
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
